### ISSUE TITLE
Why the library depends on both `LodePNG` and `stb_image`?

### ISSUE THREAD

**Issue by zapolnov** [bkaradzic/bimg#1]
Hi there!

Just got curious why `bimg` depends on both these libraries while `stb_image` handles PNG files quite well.

**Comment by bkaradzic** [comment]
STB doesn't have support for 16-bit PNGs.

**Comment by zapolnov** [comment]
The latest version does and they even added 'stbi_load_16' if you want to get real 16bit and not downscale to 8.
