### ISSUE TITLE
Recently added ASTC support causing MinGW build issues

### ISSUE THREAD

**Issue by Crunkle** [bkaradzic/bimg#16]
Whilst attempting to build `bgfx` using `mingw-gcc-release64` and, as a result, the associated `bimg_encode` dependency, an error occurs due to the recent commit 03ad392 adding new third-party sources.

![](https://cdn.jared.im/RoyalTS_2018-07-30_17-27-10.png)

> In file included from ../../../../bimg/3rdparty/astc/astc_codec_internals.h:22:0,
>                  from ../../../../bimg/3rdparty/astc/astc_averages_and_directions.cpp:17:
> ../../../../bimg/3rdparty/astc/mathlib.h:30:7: warning: "_MSC_VER" is not defined [-Wundef]
>  #if (!_MSC_VER) && (__cplusplus < 201103L)
>        ^~~~~~~~
> In file included from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/cmath:45:0,
>                  from /usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/include/c++/math.h:36,
>                  from ../../../../bimg/3rdparty/astc/astc_averages_and_directions.cpp:19:
> /usr/share/mingw-w64/include/math.h: In function ‘int __isnanl(long double)’:
> /usr/share/mingw-w64/include/math.h:573:65: error: lvalue required as left operand of assignment
>      xx = (int) (ld.ldt->lh.low | (ld.ldt->lh.high & 0x7fffffffu)); /* explicit */
>                                                                  ^

Unsure whether this is a bug in MinGW or improper use of the headers - it is preventing the build either way and the only non-intrusive solution is to rollback to an older version.

**Comment by cloudwu** [comment]
I fix this issue, see https://github.com/bkaradzic/bimg/pull/17
