### ISSUE TITLE
meh, MSVC warning treated as error #pragma warning(push) mismatch

### ISSUE THREAD

**Issue by yibbidy** [bkaradzic/bimg#32]
I noticed a mismatched #pragma warning(push) #pragma warning(pop) in tinyexr.h regarding the MINIZ_HEADER_FILE_ONLY macro on a Win build:

tinyexr.h
1891 #ifndef MINIZ_HEADER_FILE_ONLY
...
4453 #pragma warning(push)
...
6925 #endif  // MINIZ_HEADER_FILE_ONLY
...
6961 #pragma warning(pop)             <--- that should be in the MINIZ_HEADER_FILE_ONLY scope

**Comment by bkaradzic** [comment]
Report this issue here: https://github.com/syoyo/tinyexr
