### ISSUE TITLE
Incorrect layer size used in imageWriteKtx()

### ISSUE THREAD

**Issue by goodartistscopy** [bkaradzic/bimg#34]
The first overload of imageWriteKtx() is writting the image content layer by layer, but still passing the size of the whole image for each one ([link to source](https://github.com/bkaradzic/bimg/blob/dc4d1f53451a532ec04a97938b0fd235e1fcc3c4/src/image.cpp#L5608-L5609)):
```
total += bx::write(_writer, src, size, _err);
src += size;
```
Those lines should be:
```
total += bx::write(_writer, src, mipSize, _err);
src += mipSize;
```
(The 2nd overload is correct in this regard)

**Comment by bkaradzic** [comment]
Send PR with fix.
