### ISSUE TITLE
lodepng is way slower than stb. 

### ISSUE THREAD

**Issue by volcoma** [bkaradzic/bimg#6]
According to my mesurements and a couple of other people - lodepng is way slower than stb and libpng in both with/without optimizations its actually 2-3 times slower. Is there a reason why are you using it over stb?

**Comment by bkaradzic** [comment]
Because lodepng supports all PNG bit depths and colortypes. STB deals only with 8-bit RGBA.

**Comment by volcoma** [comment]
Doesn't libpng does that as well? I am not so familiar with it though but I know its the fastest one.

**Comment by bkaradzic** [comment]
You can send pull request once you integrate it.

**Comment by volcoma** [comment]
:D It has the worst api though :D

**Comment by bkaradzic** [comment]
Well... ;)
