### ISSUE TITLE
KTX loading incorrectly ignores srgb meta data

### ISSUE THREAD

**Issue by EvilTrev** [bkaradzic/bimg#78]
When loading KTX files that contain RGBA_SRGB data, parseFnT in image.cpp will correctly identify the srgb type and set it to true. However, the next step in imageParseT creates the output image container and makes no effort to copy this parameter to the output image. The contents of the file are loaded using memcpys, so no data transform occurs, the meta data is simply lost.

```
if (!parseFnT(imageContainer, &reader, _err) )        /// <<< ======= image container has srgb set
{
	return NULL;
}

ImageContainer* output = imageAlloc(_allocator        /// <<< ======= output does not
	, imageContainer.m_format
	, uint16_t(imageContainer.m_width)
	, uint16_t(imageContainer.m_height)
	, uint16_t(imageContainer.m_depth)
	, imageContainer.m_numLayers
	, imageContainer.m_cubeMap
	, 1 < imageContainer.m_numMips
);
```

**Comment by EvilTrev** [comment]
Locally, I've added:

**Comment by bkaradzic** [comment]
Looks fine. Send PR.
