### ISSUE TITLE
resize image with some resolution(like: 224x323) will casue assert in stb_image_resize.h

### ISSUE THREAD

**Issue by junjie020** [bkaradzic/bimg#87]
Build a texturec in debug mode, and use this command line:

texturec.exe -f d:/test.png -o d:/main.dds  -t BC3 -q fastest --max 256 -m

It will cause assert in stb_image_resize.h:
https://github.com/bkaradzic/bimg/blob/master/3rdparty/stb/stb_image_resize.h#L1106

I try to update stb_image_resize.h from:
https://github.com/nothings/stb/blob/master/deprecated/stb_image_resize.h

It fix this issue.

![test](https://github.com/bkaradzic/bimg/assets/1544217/4687ecdf-298e-49c2-9f1d-efdfe16608d7)

**Comment by bkaradzic** [comment]
Updated:
https://github.com/bkaradzic/bimg/commit/02356d893f7969172ef54642faf1b73d6895b48e
